"""Generate the benchmark tables referenced in BLUEPRINT.md (§13, §14).
Run:  python3 tables.py > ../results/tables.md
All numbers are computed here; nothing is copied from the literature except
the code definitions (defining sets) listed in codes.py.
"""
import math
from polyfp import deg
from orbits import orbit_census, N_from_census, N_divisor, tn_affine_messages, N_from_cosets, ord_from_cosets
from codes import all_instances, min_distance


def fmt_census(c):
    return ", ".join(f"{cnt}x{s}" for s, cnt in sorted(c.items()))


def main():
    inst = all_instances()
    print("# Computed tables for the marker-capacity blueprint\n")
    print("Generated by `verify/tables.py`. Code definitions: `verify/codes.py`.\n")

    print("## T1. Benchmark instances (binary, from source-paper families)\n")
    print("| name | C | D | r = k_D - k_C | ord(f) | orbit census of R_f\\{0} (count x size) | provenance |")
    print("|---|---|---|---|---|---|---|")
    for I in inst:
        n = I["n"]
        dC = min_distance(I["gC"], n)
        dD = min_distance(I["gD"], n) if I["repsD"] else 1
        cen = orbit_census(I["f"], 2)
        e = max(cen)
        print(f'| {I["name"]} | [{n},{I["kC"]},{dC if dC else "OPEN"}] | [{n},{I["kD"]},{dD}] | {deg(I["f"])} | '
              f'{e} | {fmt_census(cen)} | {I["source"]} |')

    print("\n## T2. Marker capacity N_f(L) vs. prior constructions\n")
    print("FTW = Fujiwara–Tonchev–Wong 2013 (one marker, L <= ord f); "
          "T–N = Tansuwannont–Nemec arXiv:2409.11312v2 Thm 5 (2^(r-L) markers, L <= r); "
          "UB = floor((2^r-1)/L).\n")
    for I in inst:
        r = deg(I["f"])
        if r > 14:
            continue
        cen = orbit_census(I["f"], 2)
        e = max(cen)
        Ls = sorted(set([2, 3, 4, 5, r, min(r + 1, e), e // 4, e // 2, e]) - {0, 1})
        print(f'\n**{I["name"]}** (r = {r}, ord f = {e})\n')
        print("| L = d_sync | FTW | T–N (Z-side) | N_f(L) (this work) | UB | log2 N_f(L) | log2 N_f(L) + log2 L |")
        print("|---|---|---|---|---|---|---|")
        for L in Ls:
            N = N_from_census(cen, L)
            ftw = 1 if L <= e else 0
            tn = tn_affine_messages(r, L)
            ub = (2 ** r - 1) // L
            print(f"| {L} | {ftw} | {tn} | {N} | {ub} | {math.log2(N):.3f} | {math.log2(N) + math.log2(L):.3f} |")

    print("\n## T3. Largest window for 2^y marker messages\n")
    print("L_TN(y) = r - y (T–N Lemma 3);  L*(y) = max{L : N_f(L) >= 2^y} (this work).\n")
    print("| instance | r | y=0 | y=1 | y=2 | y=3 | y=4 | y=5 | y=6 |")
    print("|---|---|---|---|---|---|---|---|---|")
    for I in inst:
        r = deg(I["f"])
        if r > 14:
            continue
        cen = orbit_census(I["f"], 2)
        e = max(cen)
        cells = []
        for y in range(7):
            if y > r - 1:
                cells.append("-")
                continue
            Lst = max([L for L in range(1, e + 1) if N_from_census(cen, L) >= 2 ** y] or [0])
            Ltn = r - y if r - y >= 2 else "-"
            cells.append(f"{Ltn} / {Lst}")
        print(f'| {I["name"]} | {r} | ' + " | ".join(cells) + " |")

    print("\n## T4. Non-binary instances evaluated from cyclotomic data only\n")
    print("f = prod_{i in reps} M_i; d_i = |C_i|, e_i = n/gcd(i,n).  Only the quotient f is used; "
          "the chain conditions are those claimed in the cited papers (to be re-verified, see §11).\n")
    rows = [
        ("Wang–Zhou 2025 Ex. 1", 124, 5, [3]),
        ("Liu–Kai 2023 Ex. 3.10", 80, 9, [1, 2]),
        ("Shi–Yue–Huang 2021 Ex. 2 (Table 4 rows)", 35, 29, [20]),
    ]
    print("| source | n | q | reps of f | ord(f) | N_f(2) | N_f(5) | N_f(ord f) |")
    print("|---|---|---|---|---|---|---|---|")
    for name, n, q, reps in rows:
        e = ord_from_cosets(n, q, reps)
        print(f"| {name} | {n} | {q} | {reps} | {e} | {N_from_cosets(n, q, reps, 2)} | "
              f"{N_from_cosets(n, q, reps, 5)} | {N_from_cosets(n, q, reps, e)} |")


if __name__ == "__main__":
    main()
